excluded:
    - R.generated.swift
    - Carthage
    - builds
    - .build
    - fastlane
    - Pods
    - Project/Source/Utilities/Extensions
    - Project/Resources
    - Project/Source/Utilities/Coordinator
    - Project/Source/ViewRelated/ReusableViews/CustomTabBar/CustomTabBarController.swift
    - Project/Source/Services
    
disabled_rules:
    - trailing_whitespace
    - todo
    - trailing_semicolon
    - sorted_imports
    - control_statement
    - no_space_in_method_call
    - redundant_string_enum_value
    - orphaned_doc_comment

opt_in_rules:
    - delegate
    - force_unwrapping
    - empty_count
    - empty_string
    - sorted_first_last
    - first_where
    - vertical_parameter_alignment
    - vertical_parameter_alignment_on_call
    - private_action
    - private_outlet
    - unused_optional_binding
    - unneeded_parentheses_in_closure_argument
    - trailing_comma
    - switch_case_on_newline
    - required_enum_case
    - redundant_string_enum_value
    - prefixed_toplevel_constant
    - overridden_super_call
    - multiline_parameters
    - lower_acl_than_parent
    - let_var_whitespace
    - anyobject_protocol
    - attributes
    - number_separator

analyzer_rules:
    - unused_import

identifier_name:
    allowed_symbols: "_"
    min_length: 3
    max_length:
    warning: 90
    error: 1000
    excluded:
    - id
    - URL
    severity: warning

type_body_length:
    error: 400
    warning: 300

function_body_length:
    error: 50
    warning: 49

function_parameter_count:
    error: 6
    warning: 5
    ignores_default_parameters: true

vertical_whitespace:
    max_empty_lines: 2
    warning: 2

file_length:
    warning: 450
    error: 700

line_length:
    error: 500
    warning: 450

nesting:
    type_level: 3

custom_rules:
    delegate:
    name: "Delegates weak var"
    regex: '(?<!weak\s)var\s\w*(D|d)elegate\w*:'
    message: "Pirates are better than ninjas."
    severity: error
    
    no_lines_around_braces:
    name: "No lines before or after closing curly braces"
    regex: "(\\s*{[^\\n]*)\\s*\\n{2,}(\\s*\\n)*\\s*([^\\n]*\\n\\s*})"
    message: "Don't leave lines before or after closing curly braces"
    severity: warning # or error
    correction: "$1\n$4"
